[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "de53d90"
hash = "63b6c222bf2103b3023389dde5e2ecfe"

[[plugin.deps]]
use = "pirafrank/what-size"
rev = "d896656"
hash = "62251f94eb67648d42cdfcfb8be0fad2"

[[plugin.deps]]
use = "dedukun/bookmarks"
rev = "9ef1254"
hash = "92fbb5483657fa7976cdf4e0104e18e0"

[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "0742fff"
hash = "2bd799b42b8e42b8ef100310be71f8d1"

[[plugin.deps]]
use = "kirasok/epub-preview"
rev = "2e8079e"
hash = "92d5044ae6cd823443b180477cb60733"

[[plugin.deps]]
use = "Lil-Dank/lazygit"
rev = "7a08a09"
hash = "a1fa2b3e1826c3a34804ea8c548e9f80"

[flavor]
deps = []
