# theme = "catppuccin_mocha"
theme = "tokyonight_moon"
# theme = "monokai"

[editor]
line-number = "relative"
bufferline = "always"
gutters = ["diagnostics", "line-numbers", "diff"]
auto-format = true
true-color = true
color-modes = true
idle-timeout = 150
completion-timeout = 100
end-of-line-diagnostics = "warning"

[editor.lsp]
display-inlay-hints = false
goto-reference-include-declaration = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.soft-wrap]
enable = true

[editor.file-picker]
git-ignore = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 2

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = [
  "register",
  "diagnostics",
  "position",
  "position-percentage",
  "file-type",
  "read-only-indicator",
]
separator = "│"
mode.normal = "ADID"
mode.insert = "SUPE"
mode.select = "TAMA"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[keys.normal.space]
"m" = ":buffer-close"
"." = "file_picker_in_current_buffer_directory"
"," = "buffer_picker"
"l" = "goto_last_accessed_file"
"q" = ":write-quit-all"
"z" = ":open ~/notes/notes.md"

[keys.normal]
C-r = "redo"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
"^" = "switch_to_uppercase"
"G" = "goto_last_line"
"A-h" = "goto_previous_buffer"
"A-l" = "goto_next_buffer"
"0" = "extend_to_line_start"
"$" = "extend_to_line_end"
"V" = "extend_to_line_bounds"
"_" = "extend_to_first_nonwhitespace"
# move lines up and down
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
# "d" = { "d" = ["extend_line_below", "delete_selection"] }
# A-x = "extend_to_line_bounds"
# X = ["extend_line_up", "extend_to_line_bounds"]
X = ["extend_line_above"]
esc = ["collapse_selection", "keep_primary_selection"]
C-space = ["expand_selection"]

[keys.normal.g]
o = "add_newline_below"
O = "add_newline_above"

[keys.select]
X = ["extend_line_above"]

[keys.insert.j]
"j" = "normal_mode"
