###################################################### Language definitions
[[language]]
name = "markdown"

[[language]]
name = "python"
auto-format = true
language-servers = ["basedpyright", "ruff"]
formatter = { command = "bash", args = [
  "-c",
  "ruff check --select I --fix - | ruff format - ",
] }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.basedpyright.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
auto-format = true
formatter = { command = "bash", args = ["-c", " prettier --parser yaml"] }

[[language]]
name = "docker-compose"
file-types = ["docker-compose"]
auto-format = true
formatter = { command = "bash", args = ["-c", " prettier --parser yaml"] }

[[language]]
name = "html"
file-types = ["html", "xml"]
auto-format = true
formatter = { command = "bash", args = [
  "-c",
  "prettier --stdin-filepath xx.html ",
] }

[[language]]
name = "lua"
file-types = ["lua"]
auto-format = true
language-servers = ["luals"]

[[language]]
name = "bash"
auto-format = true
language-servers = ["bash-language-server"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server"]
